In [ ]:
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/linear_regression_data_2.csv")

label = data.columns.tolist()
print(label)
x = data[label[:8]]#n+1
y = data[label[8:]]


['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'y']
          x0        x1        x2        x3        x4        x5        x6  \
0   0.818072 -0.778045  0.094980  0.033300  0.860592  0.103346 -1.731355   
1  -0.724233 -1.410975 -0.313161  0.613898  1.331972 -0.928824  1.172785   
2   0.175102  0.606430  2.828765 -0.735597  0.101352  1.139116 -0.814215   
3   0.512389  0.098131  1.169455 -0.904596 -1.192565  0.851111 -0.600206   
4  -0.328580  0.011037 -1.161826 -0.780718  0.210241 -0.574836  0.535260   
..       ...       ...       ...       ...       ...       ...       ...   
95  1.222600  0.528914  1.622452  0.488724  0.228873  0.638618  0.572499   
96  0.704985 -0.099622 -0.339692 -1.058183  1.155505 -0.069423  0.058669   
97 -0.502618 -0.067408  0.900216  0.270510 -1.245216 -0.995567 -0.099011   
98 -0.185240 -0.656368  1.047512  0.072505 -0.854580  1.284294 -0.708694   
99 -1.417825  0.410856  0.127341  0.536478  2.673749  0.578690 -0.796586   

          x7  
0  -0.725110  
1  

In [ ]:
pca = PCA(n_components=8)
Y = pca.fit_transform(x)


[[-6.50511398e-01 -2.52500115e-01 -1.60474717e+00 -1.72506650e-01
  -9.11325570e-01  9.76323422e-01  6.55675460e-01 -1.51886027e-01]
 [ 1.72584214e+00 -4.01211884e-01  4.32897889e-01 -1.15237322e+00
  -3.46299601e-01  1.21419156e+00 -1.19268463e+00  2.76689937e-01]
 [-1.52863944e+00  2.16956177e+00 -1.64263228e-01 -3.06852210e-02
   7.68111773e-01  5.30839090e-01  1.40163250e+00 -9.48735351e-01]
 [-1.63702450e+00  6.67802870e-01  2.03002979e-01 -4.97821122e-01
   4.06376236e-01 -5.27993137e-01  9.52493140e-01  5.13396683e-01]
 [ 1.84624995e-03 -1.63500738e+00  4.20705684e-01  2.59819469e-01
   1.89917712e-01  1.53240209e-01 -5.00683364e-01 -8.83786321e-01]
 [ 2.13809777e-01  3.72957390e+00 -1.30554321e+00  9.77116259e-01
  -1.42426108e+00 -4.64877270e-02  6.36494960e-02 -1.11796606e+00]
 [-2.00183273e+00  1.20595893e+00  1.13524357e-01 -3.68719364e-02
  -1.95097604e-01 -1.00210160e+00 -1.07840497e+00 -1.86750873e+00]
 [ 7.52343670e-01  1.82994238e-01 -5.59301116e-01  8.53161229e-01
  -

In [ ]:
#network
#edge -> [start, next]

def pagerank(edges, n_nodes, beta=0.85, epoch=100):
  r = [1/n_nodes]* n_nodes
  d = [0]* n_nodes

  for u, _ in edges:
    d[u] += 1

  teleport = (1-beta) /n_nodes

  for _ in range(epoch):
    r_next = [teleport] * n_nodes

     #시작 노드의 점수를 끝 노드 점수에 합산
    for u, v in edges:
      r_next[v] += beta * r[u]/d[u]


    r_sum = sum(r_next)

    #정규화 dead end 처리
    for u in range(n_nodes):
      r_next[u] += (1-r_sum)/n_nodes

    r = r_next

  return r


In [ ]:
import networkx as nx
lista = [[1,2], [2,3], [3,3], [4,4], [5,5]]
print(lista)

G = nx.DiGraph()
#G.add_node(1)  # 노드 1 추가
G.add_nodes_from([0, 1, 2, 3 ])  # 여러 노드 추가

# 엣지 추가
#G.add_edge(1, 2)  # 1 -> 2
G.add_edges_from([(0, 1), (0, 2), (0, 3), (1, 0), (2, 3), (3, 1)
                  ])  # 여러 엣지 추가

# 원하는 형태의 리스트 출력
print(G.edges)

[[1, 2], [2, 3], [3, 3], [4, 4], [5, 5]]
[(0, 1), (0, 2), (0, 3), (1, 0), (2, 3), (3, 1)]


In [ ]:
pagerank(G.edges, 4, 1.0, 100)

[0.33333333333333304,
 0.3333333333333336,
 0.11111111111111129,
 0.22222222222222215]

In [ ]:
import numpy as np
from numpy import linalg

#page rank




#power iteration
array1 = np.array([[0, 0.5, 1, 0.5], [1, 0, 0, 0], [0, 0, 0, 0.5], [0, 0.5, 0, 0]])
print(array1)
r = np.array([[0.25], [0.25], [0.25], [0.25]])

for i in range(20):
  r_next = array1@r
  r_next = r_next/r_next.sum()
  r = r_next

print(r)


[[0.  0.5 1.  0.5]
 [1.  0.  0.  0. ]
 [0.  0.  0.  0.5]
 [0.  0.5 0.  0. ]]
[[0.36320496]
 [0.36419678]
 [0.09114075]
 [0.18145752]]


In [1]:
# 감쇄 계수
beta = 0.80

M = np.array([[0, 0.5, 0.5, 0], [0, 0, 0, 1], [1/3, 1/3, 0, 1/3], [0, 0, 0 ,0 ]])
print(array1)
r = np.array([[0.4], [0.3], [0.2], [0.1]])

# 행렬 크기
N = M.shape[0]

# 균등 확률 행렬 (1/N)
uniform_matrix = np.ones((N, N)) / N

# 최종 전이 행렬 A
A = beta * M + (1 - beta) * uniform_matrix

# 초기 확률 벡터
r = np.ones((N, 1)) / N
# 파워 이터레이션
for i in range(1):
    r_next = A @ r  # 행렬-벡터 곱
    r_next = r_next / r_next.sum()  # 정규화
    r = r_next

    # 정규화
    r_next = r_next / r_next.sum()
    r = r_next

print(A)
print(r_next)

NameError: name 'np' is not defined

In [ ]:
import networkx as nx
# 방향이 없는 그래프 생성
G = nx.Graph()

# 노드 추가
#G.add_node(1)  # 노드 1 추가
G.add_nodes_from(["A", "B", "C", "D", "E", "F","G", "H" ])  # 여러 노드 추가

# 엣지 추가
#G.add_edge(1, 2)  # 1 -> 2
G.add_edges_from([("A", "B"), ("B", "C"), ("A", "D"), ("C", "D"), ("E", "D"), ("E", "H"),
                  ("G", "H"), ("H", "F"), ("B", "D")])  # 여러 엣지 추가

print("Nodes:", G.nodes)
print("Edges:", G.edges)

Nodes: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
Edges: [('A', 'B'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D'), ('D', 'E'), ('E', 'H'), ('F', 'H'), ('G', 'H')]


In [ ]:
node_ = len(G.nodes)
edges = len(G.edges)
n_triangles = sum(nx.triangles(G.to_undirected()).values()) //3

density = edges*2/(node_*(node_-1))
print(n_triangles)
print(density)

degree = nx.degree_centrality(G)
#indegree = nx.in_degree_centrality(G)
#outdegree = nx.out_degree_centrality(G)
betweenness = nx.betweenness_centrality(G) #bewteen 계산량 제한
closeness = nx.closeness_centrality(G)
pagerank = nx.pagerank(G)
clustering = nx.clustering(G)
triangles = nx.triangles(G.to_undirected())
diameter = nx.diameter(G)

print(degree)
print(closeness)
print(pagerank)
print(clustering)
print(n_triangles)
print(diameter)

#effective diameter 계산
shortest_paths = dict(nx.all_pairs_shortest_path_length(G))
print(shortest_paths)


list_a = []
for node, distances in shortest_paths.items():
    max_value = 0  # 최대값 초기화
    for neighbor, distance in distances.items():
        if max_value < distance:
            max_value = distance
    list_a.append(max_value)



i = len(list_a) *0.9
i = round(i-1)


sorted_list = sorted(list_a)
print(sorted_list)
print(sorted_list[i])

2
0.32142857142857145
{'A': 0.2857142857142857, 'B': 0.42857142857142855, 'C': 0.2857142857142857, 'D': 0.5714285714285714, 'E': 0.2857142857142857, 'F': 0.14285714285714285, 'G': 0.14285714285714285, 'H': 0.42857142857142855}
{'A': 0.4117647058823529, 'B': 0.4375, 'C': 0.4117647058823529, 'D': 0.5833333333333334, 'E': 0.5833333333333334, 'F': 0.35, 'G': 0.35, 'H': 0.5}
{'A': 0.10210232147688472, 'B': 0.1471866459281745, 'C': 0.10210232147688472, 'D': 0.1959983606706071, 'E': 0.11472410057179398, 'F': 0.07307465335251019, 'G': 0.07307465335251019, 'H': 0.1917369431706345}
{'A': 1.0, 'B': 0.6666666666666666, 'C': 1.0, 'D': 0.3333333333333333, 'E': 0, 'F': 0, 'G': 0, 'H': 0}
2
4
{'A': {'A': 0, 'B': 1, 'D': 1, 'C': 2, 'E': 2, 'H': 3, 'G': 4, 'F': 4}, 'B': {'B': 0, 'A': 1, 'C': 1, 'D': 1, 'E': 2, 'H': 3, 'G': 4, 'F': 4}, 'C': {'C': 0, 'B': 1, 'D': 1, 'A': 2, 'E': 2, 'H': 3, 'G': 4, 'F': 4}, 'D': {'D': 0, 'A': 1, 'C': 1, 'E': 1, 'B': 1, 'H': 2, 'G': 3, 'F': 3}, 'E': {'E': 0, 'D': 1, 'H': 1,

In [ ]:
print(clustering)

{'A': 1.0, 'B': 0.6666666666666666, 'C': 1.0, 'D': 0.3333333333333333, 'E': 0, 'F': 0, 'G': 0, 'H': 0}


In [ ]:
# 딕셔너리 생성
result = {lst[0]: lst[1:] for lst in lists if len(lst) > 0}